apps/thecalendar/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse_lazy
from django.views.generic import CreateView, UpdateView, DetailView, ListView, TemplateView

from .forms import EventForm
from .models import Category, Event
from .views import fullcalendar_events_json, CategoryDetailView, EventCreateView, EventUpdateView
from thecaribfos.decorators import ownership_required

urlpatterns = [
    #index
    url(r'^agenda/$',
    TemplateView.as_view(
            template_name = 'thecalendar/page_agenda.html'
        ),
        name = 'agenda'
    ),

    # json for zabuto calendar
    url(r'^json$',
        fullcalendar_events_json,
        name = 'fullcalendar_json'
    ),

    # form add event
    url(r'^event/add/$',
        login_required(EventCreateView.as_view()
        ),
        name="form_event_add",
    ),

    # form update event
    url(r'^(?P<slug>[-\w]+)/update/$',
        login_required(ownership_required(EventUpdateView.as_view(), model=Event, owner_field='creation_user')
        ),
        name = 'form_event_update'
    ),

    # event details
    url(r'^(?P<slug>[-\w]+)/$',
        DetailView.as_view(model = Event,
                           context_object_name='event',
                           template_name ='thecalendar/event_detail.html'
        ),
        name = 'event_detail'
    ),


    # Category details
    url(r'^categories/(?P<slug>[-\w\d]+)/$',
        CategoryDetailView.as_view(),
        name = 'category_detail'
    ),

    # Categories list
    url(r'^categories/$',
        ListView.as_view(
            model = Category,
            context_object_name = 'categories',
        ),
        name = "category_list"
    ),
]

apps/thecarib/urls.py
from django.conf.urls import url
#~ from django.core.urlresolvers import reverse_lazy
from django.views.generic import DetailView, ListView
#~
#~
#~ from apps.thedirectory.models import Entry
#~ from apps.thecalendar.models import Event
#~
from .models import Country

from .views import CountryDetail

urlpatterns = [

    url(r'^$',
        ListView.as_view(
            model = Country,
            context_object_name = 'countries'
        ),
        name = 'country_list'
    ),

    url(r'^(?P<slug>[-\w\d]+)/$',
        CountryDetail.as_view(),
        #~ DetailView.as_view(
            #~ model = Country,
            #~ context_object_name = 'country',
            #~ slug_field = 'iso'
        #~ ),
        name = 'country_detail'
    ),

]

apps/thedirectory/urls.py
from django.conf.urls import patterns, include, url
from django.core.urlresolvers import reverse_lazy
from django.contrib.auth.decorators import login_required
from django.views.generic import DetailView, CreateView, ListView, TemplateView

from .forms import EntryForm
from .models import Category, Entry
from .views import CategoryDetailView, EntryCreateView, EntryUpdateView, json_map_entries_by_tags
from thecaribfos.decorators import ownership_required

urlpatterns = [

    # entry details
    url(r'^entries/(?P<slug>[-\w\d]+)/$',
        DetailView.as_view(
            model = Entry,
            context_object_name = 'entry',
            slug_field = 'slug'
        ),
        name = 'entry_detail'
    ),
    # form add entry
    url(r'^entry/add/$',
        login_required(
            EntryCreateView.as_view()
        ),
        name="form_entry_add",
    ),
    # form update entry
    url(r'^entries/(?P<slug>[-\w\d]+)/update/$',
        login_required(ownership_required(EntryUpdateView.as_view(), model=Entry, owner_field='creation_user')
        ),
        name="form_entry_update",
    ),

    # Category details
    url(r'^categories/(?P<slug>[-\w\d]+)/$',
        CategoryDetailView.as_view(),
        name = 'category_detail'
    ),

    # Categories list
    url(r'^categories/$',
        ListView.as_view(
            model = Category,
            context_object_name = 'categories',
        ),
        name = "category_list"
    ),

    # index
    url(r'^map/$',
        TemplateView.as_view(
            template_name = 'thedirectory/map/page_map.html'
        ),
        #~ CreateView.as_view(
            #~ form_class=EntryForm,
            #~ template_name='thedirectory/map/page_map.html',
            #~ success_url=reverse_lazy('success')
        #~ ),
        name = 'map'
    ),
    # (leaflet POI js)
    url(r'^map.js$',
        ListView.as_view(model = Entry,
                         template_name = 'thedirectory/map/map.js'
        ),
        name="map_js"
    ),
    url(r'^map_home.js$',
        ListView.as_view(model = Entry,
                         template_name = 'thedirectory/map/map_home.js'
        ),
        name="map_js"
    ),
    url(r'^map/tag/(?P<tag>[-_A-Za-z0-9]+)/entries.json$',
        json_map_entries_by_tags,
        name = 'json_map_entries_by_tags'
    ),


    #~ (r'^tags/$', 'apps.thedirectory.views.tags'),
    #~ (r'^tag/(?P[-_A-Za-z0-9]+)/$','apps.thedirectory.views.with_tag'),
    #~ (r'^tag/(?P[-_A-Za-z0-9]+)/page/(?Pd+)/$', 'apps.thedirectory.views.with_tag' ),
]

thecaribfos/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.contrib.flatpages import views
from django.views.generic import ListView, TemplateView
from django.views.i18n import javascript_catalog

import autocomplete_light.shortcuts as al
from apps.thecalendar.models import Event
from apps.thehomepage.views import HomePageDetailView

js_info_dict = {
    'packages': ('thecaribfos.apps.thedirectory',),
}

urlpatterns = [
    # main index
    url(r'^$',
        #~ ListView.as_view(
            #~ model = Event,
            #~ template_name = 'home.html'
        #~ ),
        HomePageDetailView.as_view(),
        name = 'home'
    ),
    url(r'^calendar/', include("apps.thecalendar.urls", namespace="thecalendar")),
    url(r'^directory/', include("apps.thedirectory.urls", namespace="thedirectory")),

    url(r'^caribbean/', include("apps.thecarib.urls", namespace="thecarib")),
    url(r'^contact/', include('apps.thecontactform.urls', namespace="thecontactform")),

    url(r'^account/', include("account.urls")),
    url(r'^account/$', login_required(TemplateView.as_view(
            template_name = 'account/profile.html')
        ),
        name = 'account_profile'
    ),
    url(r"^account/social/", include("social.apps.django_app.urls", namespace="social")),
    url(r'^user/', include('apps.theuser.urls', namespace='theuser')),
    url(r'^admin/', include(admin.site.urls)),
    # form submission success
    url(r'^contribute/success/$',
        TemplateView.as_view(template_name="include/success.html"),
        name='success'
    ),
    #~ url(r'^markdown/', include('django_bootstrap_markdown.urls')),
    url(r'^autocomplete/', include('autocomplete_light.urls')),
    url(r'^jsi18n/$', javascript_catalog, js_info_dict),
    #~ url(r'^(?P<url>.*/)$', views.flatpage),
]

apps/thecalendar/models.py
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.utils.translation import ugettext as _
from django.contrib.auth.models import User
from taggit.managers import TaggableManager

from apps.thecarib.models import Country

@python_2_unicode_compatible
class Category(models.Model):
    name = models.CharField(_("Name"),
                             max_length=25)
    slug = models.SlugField(_("Slug"),
                            max_length=25)
    description = models.TextField(_("Description"),
                                   max_length=250)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ["name"]
        verbose_name_plural = "Categories"

@python_2_unicode_compatible
class Event(models.Model):

    DRAFT = 'draft'
    PENDING = 'pending'
    PUBLISHED = 'published'
    PUB_STATUS_CHOICES = (
        (DRAFT, _('draft')),
        (PENDING, _('pending')),
        (PUBLISHED, _('published')),
    )

    TENTATIVE = 'tentative'
    CONFIRMED = 'confirmed'
    CANCELLED = 'cancelled'
    STATUS_CHOICES = (
        (TENTATIVE, _("tentative")),
        (CONFIRMED, _("confirmed")),
        (CANCELLED, _("cancelled")),
    )

    country = models.ForeignKey(Country)
    category = models.ForeignKey(Category)
    tags = TaggableManager(verbose_name = _("Tag(s)"),
                           blank=True)
    creation_user = models.ForeignKey(User)
    status = models.CharField(_("Status"),
                              max_length=10,
                              choices=STATUS_CHOICES,
                              default=PENDING)
    dtstart = models.DateTimeField(_("From"))
    dtend = models.DateTimeField(_("To"))
    allday = models.BooleanField(_("All day"))
    summary = models.CharField(_("Title"),
                               max_length=75)
    description = models.TextField(_("Description"),
                                   help_text=_("Use Markdown to format you description text"))
    email = models.EmailField(_("Email"),
                              help_text=_("Email are not published on the website."))
    web = models.URLField(_("Web"),
                               max_length=250)
    #~ location = models.CharField(_("Location"),
                                    #~ max_length=250)
    lat = models.FloatField(_("Latitude"), null=True)
    lon = models.FloatField(_("Longitude"), null=True)
    address = models.TextField(_("Address"),
                               max_length=250)

    slug = models.SlugField(_("Slug"),
                            max_length=100)
    sequence = models.SmallIntegerField(_("Update number"), default=0)
    creation_date = models.DateTimeField(_("Created on"),
                                         auto_now_add=True)
    lastupdate_date = models.DateTimeField(_("Last modification"),
                                         auto_now=True)
    pub_status = models.CharField(_("Publication status"),
                                  max_length=10,
                                  choices=PUB_STATUS_CHOICES,
                                  default=PENDING)

    def __str__(self):
        return self.summary

    def save(self, *args, **kwargs):
        ''' increases the sequence number
        '''
        self.sequence += 1
        super(Event, self).save(*args, **kwargs)

    class Meta:
        ordering = ["dtstart", "country", "summary" ]

apps/thecarib/models.py
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.utils.translation import ugettext as _

@python_2_unicode_compatible
class Country(models.Model):
    name = models.CharField(_("Name"),
                            max_length=75)

    iso = models.SlugField(_("Iso code"),
                            max_length="5",
                            help_text=_("iso 3166 code"),
                            unique=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ["name"]
        verbose_name_plural = "Countries"

apps/thedirectory/models.py
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.utils.translation import ugettext as _
from django.contrib.auth.models import User
from taggit.managers import TaggableManager
from apps.thecarib.models import Country

@python_2_unicode_compatible
class Category(models.Model):
    name = models.CharField(_("Name"),
                             max_length=75)
    slug = models.SlugField(_("Slug"),
                            max_length=25)
    description = models.TextField(_("Description"),
                                   max_length=250,
                                   blank=True)
    def __str__(self):
        return self.name

    class Meta:
        ordering = ["name"]
        verbose_name_plural = "Categories"

@python_2_unicode_compatible
class Entry(models.Model):
    name = models.CharField(_("Name"),
                             max_length=75)
    slug = models.SlugField(_("Slug"),
                            max_length=100)
    country = models.ForeignKey(Country)
    category = models.ForeignKey(Category)
    tags = TaggableManager(verbose_name = _("Tag(s)"),
                           blank=True)
    creation_user = models.ForeignKey(User)
    description = models.TextField(_("Description"),
                                   help_text=_("Use Markdown to format you description text"))
    address = models.TextField(_("Address"), null=True, blank=True)
    email = models.EmailField(_("Email"),
                              help_text=_("Email are not published on the website."))
    web = models.URLField(_("Web"),
                               max_length=250)
    lat = models.FloatField(_("Latitude"), null=True)
    lon = models.FloatField(_("Longitude"), null=True)
    sequence = models.SmallIntegerField(_("Update number"), default=0)
    creation_date = models.DateTimeField(_("Created on"),
                                         auto_now_add=True)
    lastupdate_date = models.DateTimeField(_("Last modification"),
                                         auto_now=True)

    twitter =  models.CharField(_("Twitter account"),
                             max_length=75,
                             null=True,
                             blank=True)
    facebook = models.CharField(_("Facebook page"),
                             max_length=75,
                             null=True,
                             blank=True)
    googleplus = models.CharField(_("Google plus page"),
                             max_length=75,
                             null=True,
                             blank=True)
    linkedin = models.CharField(_("LinkedIn page"),
                             max_length=75,
                             null=True,
                             blank=True)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        ''' increases the sequence number
        '''
        self.sequence += 1
        super(Entry, self).save(*args, **kwargs)

    class Meta:
        ordering = ["name", "country"]
        verbose_name_plural = "Entries"

apps/thecarib/views.py
from django.views.generic import DetailView

from .models import Country
from apps.thedirectory.models import Entry
from apps.thecalendar.models import Event


class CountryDetail(DetailView):

    model = Country
    context_object_name = 'country'
    slug_field = 'iso'

    def get_context_data(self, **kwargs):
        context = super(CountryDetail, self).get_context_data(**kwargs)
        context['event_list'] = Event.objects.filter(country=self.object)
        context['entry_list'] = Entry.objects.filter(country=self.object)
        context['country_list'] = Country.objects.all().order_by('?')[:3]

        return context

apps/thecarib/templates/thecarib/country_detail.html
{% extends 'include/page_panel.html' %}
{% load staticfiles %}
{% load i18n %}
{% load slug2js %}
{% load endless %}


{% block head_title %}{{ country.name }}{% endblock %}

{% block head %}
{% include "thedirectory/map/map_page_header.html" %}
<link rel='stylesheet' href="{% static 'libs/bower_components/fullcalendar/dist/fullcalendar.css' %}"/>
{% endblock %}

{% block content-title %}{{ country.name }}{% endblock %}

{% block panel-title %}<a href="{% url 'thecarib:country_list' %}">{% trans 'Caribbean' %}</a> /  {{ country.name }}{% endblock %}

{% block panel-body %}
<div class="col-md-6">
    <h3 class="page-header"><i class="fa fa-rocket"> </i> {% trans 'Organizations and people' %}</h3>
    <div class="list-group">{% lazy_paginate 5 entry_list using 'entries_at_page' %}{% for entry in entry_list %}
      <a href="{% url 'thedirectory:entry_detail' entry.slug %}" class="list-group-item">
        <h4 class="list-group-item-heading">{{ entry.name }}</h4>
        <p class="list-group-item-text"><small>{{ entry.category.name }}</small></p>
        <p class="list-group-item-text btn-link">{{ entry.description|slice:":150" }}</p>
      </a>
    {% empty %}
    <p>{% blocktrans with country_name=country.name %}Sorry, no entry registered yet in {{ country_name }} in Caribbean Free Open Source organization and people directory{% endblocktrans %}</p>
    {% endfor %}{% show_pages %}
    </div>
    <p><a class="btn btn-primary" href="{% url 'thedirectory:form_entry_add' %}" role="button">{% trans 'Add a new organization or people' %}</a></p>
</div>
<div class="col-md-6">
    {% if event_list|length < 1 %}
    <h3 class="page-header"><i class="fa fa-random"> </i> {% trans 'Coming Events' %}</h3>
    <p>{% blocktrans with country_name=country.name %}Sorry, no coming events scheduled in Caribbean Free Open Source calendar for {{ country_name }}.{% endblocktrans %}</p>
    <p><a class="btn btn-primary" href="{% url 'thecalendar:form_event_add' %}" role="button">{% trans 'Add a new date' %}</a>
    <a class="btn btn-link" href="{% url 'thecalendar:agenda' %}?country={{ country.iso }}">{% blocktrans with country_name=country.name %}See calendar {{ country_name }}{% endblocktrans %}</a></p>
    {% endif %}
    {% if event_list|length > 1 %}
    <h3 class="page-header"><i class="fa fa-random"> </i> {% trans 'Coming Events' %}</h3>
    {% endif %}
    <div class="list-group">{% lazy_paginate 5 event_list using 'events_at_page' %}{% for event in event_list %}
      <a href="{% url 'thecalendar:event_detail' event.slug %}" class="list-group-item">
        <h4 class="list-group-item-heading">{{ event.summary }}</h4>
        <p class="list-group-item-text"><small>{{ event.dtstart }}{% if event.dtend != event.dtstart %} - {{ event.dtend }}{% endif %}</small></p>
        <p class="list-group-item-text btn-link">{{ event.description|slice:":150" }}</p>
      </a>
    {% endfor %}{% show_pages %}
    </div>
</div>
{% endblock %}

{% block osmmap %}<div style="height:350px;" id="map"></div><br>{% endblock %}

{% block see-also %}
    {% for country in country_list %}
    <li><strong><a href="{% url 'thecarib:country_detail' country.iso %}">{{ country.name|upper }}</a></strong></li>
    {% endfor %}
{% endblock %}

{% block footer-js %}
<script>
    var map = new L.map('map',{fullscreenControl: false,
                                scrollWheelZoom: false,
                                fullscreenControlOptions:{position: 'topleft'}
                              }).setView([19.031, -73.048], 4);
    L.tileLayer('http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
        maxZoom: 18,
        attribution: 'Map data &copy; <a href="http://openstreetmap.org">OpenStreetMap</a> contributors, ' +
            '<a href="http://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>'
    }).addTo(map);
    var markers = L.markerClusterGroup();

    {% for entry in entry_list %}
        {% if entry.lat %}
        var marker = L.marker(new L.LatLng({{ entry.lat }}, {{ entry.lon }}), { title: "{{ entry.name }}" });
        var popup = "<h3>{{ entry.name }}</h3>{% if entry.tags %}<ul class=\"list-inline\">{% for tag in entry.tags.slugs %}<li>#{{ tag }}</li>{% endfor %}</ul><p>{{ entry.category }}</p><p class=\"text-right\"><a href=\"/directory/entries/{{ entry.slug }}/\" class=\"small\">Read more <i class=\"fa fa-arrow-circle-right\"></i></a></p>{% endif %}";
        marker.bindPopup(popup);
        markers.addLayer(marker);
        {% endif %}
    {% endfor %}
    {% for event in event_list %}
        {% if event.lat %}
        var marker = L.marker(new L.LatLng({{ event.lat }}, {{ event.lon }}), { title: "{{ event.summary }}" });
        markers.addLayer(marker);
        {% endif %}
    {% endfor %}

    map.addLayer(markers);
    map.on();
</script>
<script src="{% static 'libs/bower_components/moment/min/moment.min.js' %}"></script>
<script src="{% static 'libs/bower_components/fullcalendar/dist/fullcalendar.js' %}"></script>
<script src="/static/libs/bower_components/fullcalendar/dist/lang/{% get_current_language as LANGUAGE_CODE %}{{ LANGUAGE_CODE }}.js"></script>
<script type="application/javascript">
    $(document).ready(function() {
    $('#calendar').fullCalendar({
            contentHeight: 'auto',
            header: {
                left: 'prev,next today',
                center: 'title',
                right: 'month,agendaWeek,agendaDay'
            },
            defaultDate: '{% now "Y-m-d" %}',
            selectable: true,
            selectHelper: true,
            select: function(start, end) {
                var eventData;
                if (title) {
                    eventData = {
                        title: title,
                        start: start,
                        end: end
                    };
                    $('#calendar').fullCalendar('renderEvent', eventData, true); // stick? = true
                }
                $('#calendar').fullCalendar('unselect');
            },
            editable: false,
            eventLimit: false, // allow "more" link when too many events
            events: '{% url "thecalendar:fullcalendar_json" %}?country={{ country.iso }}'
    })
});
</script>


{% endblock %}

apps/thecarib/templates/thecarib/country_list.html
{% extends 'include/page_panel.html' %}
{% load staticfiles %}
{% load i18n %}

{% block head_title %}{% trans "Caribbean" %}{% endblock %}

{% block head %}
{% include "thedirectory/map/map_page_header.html" %}
{% endblock %}

{% block content-title %}{% trans "Caribbean" %}{% endblock %}

{% block panel-title %}{% trans 'Caribbean' %}{% endblock %}


{% block panel-body %}
    <div class="col-lg-6">
    <ul>{% for country in countries %}
        <li><a href="{% url 'thecarib:country_detail' slug=country.iso %}">{{ country.name }}</a>
        </li>
    {% endfor %}</ul>
    </div>
    <div class="col-lg-6">
        <div class="alert alert-thecaribfos" role="alert">
            <h4>Caribbean</h4>
            <p>The <b>Caribbean</b> (<i>/ˌkærɨˈbiːən/</i> or <i>/kəˈrɪbiən/</i>; Spanish: <i>Caribe</i>; Dutch: <i>Caraïben</i> ; French: <i>Caraïbe</i> or more commonly <i>Antilles</i>) is a region that consists of the Caribbean Sea, its islands (some surrounded by the Caribbean Sea and some bordering both the Caribbean Sea and the North Atlantic Ocean), and the surrounding coasts. The region is southeast of the Gulf of Mexico and the North American mainland, east of Central America, and north of South America.</p>
            <p class="small">Situated largely on the Caribbean Plate, the region comprises more than 700 islands, islets, reefs, and cays. These islands generally form island arcs that delineate the eastern and northern edges of the Caribbean Sea. The Caribbean islands, consisting of the Greater Antilles on the north and the Lesser Antilles on the south and east (including the Leeward Antilles), are part of the somewhat larger <b>West Indies</b> grouping, which also includes the Lucayan Archipelago (comprising The Bahamas and Turks and Caicos Islands) north of the Greater Antilles and Caribbean Sea. In a wider sense, the mainland countries of Belize, Guyana, and Suriname may be included.</p>
            <p class="small">Geopolitically, the Caribbean islands are usually regarded as a subregion of North America and are organized into 30 territories including sovereign states, overseas departments, and dependencies.</p>
            <p class="small">source : <a href="https://en.wikipedia.org/wiki/Caribbean">wikipedia.org</a></p>
        </div>
    </div>

{% endblock %}

{% block osmmap %}<div style="height:350px;" id="map"></div><br>{% endblock %}

{% block panel-footer %}The caribbean free open source organizations and people directory{% endblock %}

{% block see-also %}
    <ul>
        <li><a href="{% url 'thedirectory:category_list' %}">{% trans 'The directory entries categories' %}</a></li>
        <li><a href="{% url 'thecalendar:category_list' %}">{% trans 'The events categories' %}</a></li>
{% endblock %}</ul>

{% block footer-js %}
{% include "thedirectory/map/map_page_footer.html" %}
{% endblock %}