apps/thecalendar/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse_lazy
from django.views.generic import CreateView, UpdateView, DetailView, ListView, TemplateView

from .forms import EventForm
from .models import Category, Event
from .views import fullcalendar_events_json, CategoryDetailView, EventCreateView, EventUpdateView
from thecaribfos.decorators import ownership_required

urlpatterns = [
    #index
    url(r'^agenda/$',
    TemplateView.as_view(
            template_name = 'thecalendar/page_agenda.html'
        ),
        name = 'agenda'
    ),

    # json for zabuto calendar
    url(r'^json$',
        fullcalendar_events_json,
        name = 'fullcalendar_json'
    ),

    # form add event
    url(r'^event/add/$',
        login_required(EventCreateView.as_view()
        ),
        name="form_event_add",
    ),

    # form update event
    url(r'^(?P<slug>[-\w]+)/update/$',
        login_required(ownership_required(EventUpdateView.as_view(), model=Event, owner_field='creation_user')
        ),
        name = 'form_event_update'
    ),

    # event details
    url(r'^(?P<slug>[-\w]+)/$',
        DetailView.as_view(model = Event,
                           context_object_name='event',
                           template_name ='thecalendar/event_detail.html'
        ),
        name = 'event_detail'
    ),


    # Category details
    url(r'^categories/(?P<slug>[-\w\d]+)/$',
        CategoryDetailView.as_view(),
        name = 'category_detail'
    ),

    # Categories list
    url(r'^categories/$',
        ListView.as_view(
            model = Category,
            context_object_name = 'categories',
        ),
        name = "category_list"
    ),
]

apps/thecarib/urls.py
from django.conf.urls import url
#~ from django.core.urlresolvers import reverse_lazy
from django.views.generic import DetailView, ListView
#~
#~
#~ from apps.thedirectory.models import Entry
#~ from apps.thecalendar.models import Event
#~
from .models import Country

from .views import CountryDetail

urlpatterns = [

    url(r'^$',
        ListView.as_view(
            model = Country,
            context_object_name = 'countries'
        ),
        name = 'country_list'
    ),

    url(r'^(?P<slug>[-\w\d]+)/$',
        CountryDetail.as_view(),
        #~ DetailView.as_view(
            #~ model = Country,
            #~ context_object_name = 'country',
            #~ slug_field = 'iso'
        #~ ),
        name = 'country_detail'
    ),

]

apps/thedirectory/urls.py
from django.conf.urls import patterns, include, url
from django.core.urlresolvers import reverse_lazy
from django.contrib.auth.decorators import login_required
from django.views.generic import DetailView, CreateView, ListView, TemplateView

from .forms import EntryForm
from .models import Category, Entry
from .views import CategoryDetailView, EntryCreateView, EntryUpdateView, json_map_entries_by_tags
from thecaribfos.decorators import ownership_required

urlpatterns = [

    # entry details
    url(r'^entries/(?P<slug>[-\w\d]+)/$',
        DetailView.as_view(
            model = Entry,
            context_object_name = 'entry',
            slug_field = 'slug'
        ),
        name = 'entry_detail'
    ),
    # form add entry
    url(r'^entry/add/$',
        login_required(
            EntryCreateView.as_view()
        ),
        name="form_entry_add",
    ),
    # form update entry
    url(r'^entries/(?P<slug>[-\w\d]+)/update/$',
        login_required(ownership_required(EntryUpdateView.as_view(), model=Entry, owner_field='creation_user')
        ),
        name="form_entry_update",
    ),

    # Category details
    url(r'^categories/(?P<slug>[-\w\d]+)/$',
        CategoryDetailView.as_view(),
        name = 'category_detail'
    ),

    # Categories list
    url(r'^categories/$',
        ListView.as_view(
            model = Category,
            context_object_name = 'categories',
        ),
        name = "category_list"
    ),

    # index
    url(r'^map/$',
        TemplateView.as_view(
            template_name = 'thedirectory/map/page_map.html'
        ),
        #~ CreateView.as_view(
            #~ form_class=EntryForm,
            #~ template_name='thedirectory/map/page_map.html',
            #~ success_url=reverse_lazy('success')
        #~ ),
        name = 'map'
    ),
    # (leaflet POI js)
    url(r'^map.js$',
        ListView.as_view(model = Entry,
                         template_name = 'thedirectory/map/map.js'
        ),
        name="map_js"
    ),
    url(r'^map_home.js$',
        ListView.as_view(model = Entry,
                         template_name = 'thedirectory/map/map_home.js'
        ),
        name="map_js"
    ),
    url(r'^map/tag/(?P<tag>[-_A-Za-z0-9]+)/entries.json$',
        json_map_entries_by_tags,
        name = 'json_map_entries_by_tags'
    ),


    #~ (r'^tags/$', 'apps.thedirectory.views.tags'),
    #~ (r'^tag/(?P[-_A-Za-z0-9]+)/$','apps.thedirectory.views.with_tag'),
    #~ (r'^tag/(?P[-_A-Za-z0-9]+)/page/(?Pd+)/$', 'apps.thedirectory.views.with_tag' ),
]

apps/theuser/urls.py
from django.conf.urls import patterns, include, url
from django.core.urlresolvers import reverse_lazy

from .views import UserDetailView

urlpatterns = [
    # user public details
    url(r'^(?P<slug>[-\w]+)/$', UserDetailView.as_view(),
    name = 'user_detail'
    ),
]

thecaribfos/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.contrib.flatpages import views
from django.views.generic import ListView, TemplateView
from django.views.i18n import javascript_catalog

import autocomplete_light.shortcuts as al
from apps.thecalendar.models import Event
from apps.thehomepage.views import HomePageDetailView

js_info_dict = {
    'packages': ('thecaribfos.apps.thedirectory',),
}

urlpatterns = [
    # main index
    url(r'^$',
        #~ ListView.as_view(
            #~ model = Event,
            #~ template_name = 'home.html'
        #~ ),
        HomePageDetailView.as_view(),
        name = 'home'
    ),
    url(r'^calendar/', include("apps.thecalendar.urls", namespace="thecalendar")),
    url(r'^directory/', include("apps.thedirectory.urls", namespace="thedirectory")),

    url(r'^caribbean/', include("apps.thecarib.urls", namespace="thecarib")),
    url(r'^contact/', include('apps.thecontactform.urls', namespace="thecontactform")),

    url(r'^account/', include("account.urls")),
    url(r'^account/$', login_required(TemplateView.as_view(
            template_name = 'account/profile.html')
        ),
        name = 'account_profile'
    ),
    url(r"^account/social/", include("social.apps.django_app.urls", namespace="social")),
    url(r'^user/', include('apps.theuser.urls', namespace='theuser')),
    url(r'^admin/', include(admin.site.urls)),
    # form submission success
    url(r'^contribute/success/$',
        TemplateView.as_view(template_name="include/success.html"),
        name='success'
    ),
    #~ url(r'^markdown/', include('django_bootstrap_markdown.urls')),
    url(r'^autocomplete/', include('autocomplete_light.urls')),
    url(r'^jsi18n/$', javascript_catalog, js_info_dict),
    #~ url(r'^(?P<url>.*/)$', views.flatpage),
]

apps/thecalendar/models.py
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.utils.translation import ugettext as _
from django.contrib.auth.models import User
from taggit.managers import TaggableManager

from apps.thecarib.models import Country

@python_2_unicode_compatible
class Category(models.Model):
    name = models.CharField(_("Name"),
                             max_length=25)
    slug = models.SlugField(_("Slug"),
                            max_length=25)
    description = models.TextField(_("Description"),
                                   max_length=250)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ["name"]
        verbose_name_plural = "Categories"

@python_2_unicode_compatible
class Event(models.Model):

    DRAFT = 'draft'
    PENDING = 'pending'
    PUBLISHED = 'published'
    PUB_STATUS_CHOICES = (
        (DRAFT, _('draft')),
        (PENDING, _('pending')),
        (PUBLISHED, _('published')),
    )

    TENTATIVE = 'tentative'
    CONFIRMED = 'confirmed'
    CANCELLED = 'cancelled'
    STATUS_CHOICES = (
        (TENTATIVE, _("tentative")),
        (CONFIRMED, _("confirmed")),
        (CANCELLED, _("cancelled")),
    )

    country = models.ForeignKey(Country)
    category = models.ForeignKey(Category)
    tags = TaggableManager(verbose_name = _("Tag(s)"),
                           blank=True)
    creation_user = models.ForeignKey(User)
    status = models.CharField(_("Status"),
                              max_length=10,
                              choices=STATUS_CHOICES,
                              default=PENDING)
    dtstart = models.DateTimeField(_("From"))
    dtend = models.DateTimeField(_("To"))
    allday = models.BooleanField(_("All day"))
    summary = models.CharField(_("Title"),
                               max_length=75)
    description = models.TextField(_("Description"),
                                   help_text=_("Use Markdown to format you description text"))
    email = models.EmailField(_("Email"),
                              help_text=_("Email are not published on the website."))
    web = models.URLField(_("Web"),
                               max_length=250)
    #~ location = models.CharField(_("Location"),
                                    #~ max_length=250)
    lat = models.FloatField(_("Latitude"), null=True)
    lon = models.FloatField(_("Longitude"), null=True)
    address = models.TextField(_("Address"),
                               max_length=250)

    slug = models.SlugField(_("Slug"),
                            max_length=100)
    sequence = models.SmallIntegerField(_("Update number"), default=0)
    creation_date = models.DateTimeField(_("Created on"),
                                         auto_now_add=True)
    lastupdate_date = models.DateTimeField(_("Last modification"),
                                         auto_now=True)
    pub_status = models.CharField(_("Publication status"),
                                  max_length=10,
                                  choices=PUB_STATUS_CHOICES,
                                  default=PENDING)

    def __str__(self):
        return self.summary

    def save(self, *args, **kwargs):
        ''' increases the sequence number
        '''
        self.sequence += 1
        super(Event, self).save(*args, **kwargs)

    class Meta:
        ordering = ["dtstart", "country", "summary" ]

apps/theuser/models.py
from django.db import models

# Create your models here.

apps/theuser/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.template import RequestContext

from django.views.generic import DetailView
from apps.thedirectory.models import Entry
from apps.thecalendar.models import Event
from django.contrib.auth.models import User

class UserDetailView(DetailView):
    template_name = 'theuser/user_detail.html'
    slug_field = 'username'
    context_object_name = 'user'
    model = User

    def get_context_data(self, **kwargs):
        context = super(UserDetailView,self).get_context_data(**kwargs)

        #~ context['user'] = User.objects.get(username__exact=self.request['username'])

        #~ context['user'] = User.objects.get(username__exact='admin')
        context['entries'] = Entry.objects.filter(creation_user=self.object)
        context['events'] = Event.objects.filter(creation_user=self.object)

        return context

apps/theuser/templates/theuser/user_detail.html
{% extends 'include/page_panel.html' %}
{% load staticfiles %}
{% load i18n %}
{% load slug2js %}
{% load endless %}


{% block head_title %}{{ user.username }}{% endblock %}

{% block head %}
{% include "thedirectory/map/map_page_header.html" %}
<link rel='stylesheet' href="{% static 'libs/bower_components/fullcalendar/dist/fullcalendar.css' %}"/>
{% endblock %}

{% block content-title %}{{ user.username }}{% endblock %}

{% block panel-title %}{% blocktrans with username=user.username %}{{ username }}'s contributions to the Caribbean FOS directory and calendar.{%   endblocktrans %}{% endblock %}

{% block panel-body %}
<div class="col-md-6">
    <h3 class="page-header"><i class="fa fa-rocket"> </i> {% trans 'Directory' %} <span class="badge">{{ entries|length }}</span></h3>
    <div class="list-group">{% lazy_paginate 5 entries using 'entries_at_page' %}
    {% for entry in entries %}
      <a href="{% url 'thedirectory:entry_detail' entry.slug %}" class="list-group-item">
        <h4 class="list-group-item-heading">{{ entry.name }}</h4>
        <p class="list-group-item-text"><small class="text-muted">{{ entry.category.name }} - {{ entry.country.name }}</small></p>
        <p class="list-group-item-text btn-link">{{ entry.description|slice:":150" }}</p>
      </a>
    {% empty %}
        <p>{% blocktrans with username=user.get_full_name %}No directory entry for {{ username }}.{%   endblocktrans %}</p>
    {% endfor %}
    <br>
    <p class="text-center">{% show_pages %}</p>
    </div>
</div>
<div class="col-md-6">
    {% if events|length < 1 %}
    <h3 class="page-header"><i class="fa fa-random"> </i> {% trans 'Events' %}</h3>
    <p>{% blocktrans with username=user.username %}Sorry, no events scheduled in Caribbean Free Open Source calendar by {{ username }}.{% endblocktrans %}</p>
    {% endif %}
    {% if events|length > 1 %}
    <h3 class="page-header"><i class="fa fa-random"> </i> {% trans 'Events' %} <span class="badge">{{ events|length }}</span></h3>
    {% endif %}
    <div class="list-group">{% lazy_paginate 5 events using 'events_at_page' %}{% for event in events %}
      <a href="{% url 'thecalendar:event_detail' event.slug %}" class="list-group-item">
        <h4 class="list-group-item-heading">{{ event.summary }}</h4>
        <p class="list-group-item-text"><small class="text-muted">{{ event.category.name }} - {{ event.country.name }}</small></p>
        <p class="list-group-item-text"><small>{{ event.dtstart }}{% if event.dtend != event.dtstart %} - {{ event.dtend }}{% endif %}</small></p>
        <p class="list-group-item-text btn-link">{{ event.description|slice:":150" }}</p>
      </a>
    {% endfor %}
    <br>
    <p class="text-center">{% show_pages %}</p>
    </div>
</div>
{% endblock %}

{% block panel-footer %}
{% if user.last_login %}<div class="pull-right social-links"><i class="fa fa-calendar"> </i> {% trans "Last visite" %} : {{ user.last_login }}</div>{% endif %}
<i class="fa fa-user"> </i> {% trans "Member since" %} : {{ user.date_joined }}
{% endblock %}

{% block osmmap %}<div style="height:350px;" id="map"></div><br>{% endblock %}

{% block see-also %}
    {% for country in country_list %}
    <li><strong><a href="{% url 'thecarib:country_detail' country.iso %}">{{ country.name|upper }}</a></strong></li>
    {% endfor %}
{% endblock %}

{% block footer-js %}
<script>
    var map = new L.map('map',{fullscreenControl: false,
                                scrollWheelZoom: false,
                                fullscreenControlOptions:{position: 'topleft'}
                              }).setView([19.031, -73.048], 4);
    L.tileLayer('http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
        maxZoom: 18,
        attribution: 'Map data &copy; <a href="http://openstreetmap.org">OpenStreetMap</a> contributors, ' +
            '<a href="http://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>'
    }).addTo(map);
    var markers = L.markerClusterGroup();

    {% for entry in entry_list %}
        {% if entry.lat %}
        var marker = L.marker(new L.LatLng({{ entry.lat }}, {{ entry.lon }}), { title: "{{ entry.name }}" });
        var popup = "<h3>{{ entry.name }}</h3>{% if entry.tags %}<ul class=\"list-inline\">{% for tag in entry.tags.slugs %}<li>#{{ tag }}</li>{% endfor %}</ul><p>{{ entry.category }}</p><p class=\"text-right\"><a href=\"/directory/entries/{{ entry.slug }}/\" class=\"small\">Read more <i class=\"fa fa-arrow-circle-right\"></i></a></p>{% endif %}";
        marker.bindPopup(popup);
        markers.addLayer(marker);
        {% endif %}
    {% endfor %}
    {% for event in event_list %}
        {% if event.lat %}
        var marker = L.marker(new L.LatLng({{ event.lat }}, {{ event.lon }}), { title: "{{ event.summary }}" });
        markers.addLayer(marker);
        {% endif %}
    {% endfor %}

    map.addLayer(markers);
    map.on();
</script>
<script src="{% static 'libs/bower_components/moment/min/moment.min.js' %}"></script>
<script src="{% static 'libs/bower_components/fullcalendar/dist/fullcalendar.js' %}"></script>
<script src="/static/libs/bower_components/fullcalendar/dist/lang/{% get_current_language as LANGUAGE_CODE %}{{ LANGUAGE_CODE }}.js"></script>
<script type="application/javascript">
    $(document).ready(function() {
    $('#calendar').fullCalendar({
            contentHeight: 'auto',
            header: {
                left: 'prev,next today',
                center: 'title',
                right: 'month,agendaWeek,agendaDay'
            },
            defaultDate: '{% now "Y-m-d" %}',
            selectable: true,
            selectHelper: true,
            select: function(start, end) {
                var eventData;
                if (title) {
                    eventData = {
                        title: title,
                        start: start,
                        end: end
                    };
                    $('#calendar').fullCalendar('renderEvent', eventData, true); // stick? = true
                }
                $('#calendar').fullCalendar('unselect');
            },
            editable: false,
            eventLimit: false, // allow "more" link when too many events
            events: '{% url "thecalendar:fullcalendar_json" %}?country={{ country.iso }}'
    })
});
</script>


{% endblock %}

apps/theuser/templates/theuser/user_detail_alternate.html
{% extends "page.html" %}
{% load i18n %}
{% load tz %}

{% block head_title %}{{ user.username }}{% endblock %}

{% block main-content %}
<section id="fos-user">
<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <h2 class="text-center">{% if user.get_full_name %}
                {{ user.get_full_name }}
            {% else %}
                {{ user }}
            {% endif %}</h2>
            <hr class="star-primary">
            {% get_current_timezone as TIME_ZONE %}
            {% with tz=user.account.timezone|default:TIME_ZONE %}
        </div>
        {% timezone tz %}
    </div>
    <div class="row">
        <div class="col-md-6">
            <p class="text-muted">
                <i class="fa fa-user"> </i> {% trans "Member since" %} : {{ user.date_joined }}
            </p>
        </div>
        <div class="col-md-6">
            <p class="text-muted">
                <i class="fa fa-calendar"> </i>  {% trans "Last visite" %} : {{ user.last_login }}
            </p>
        </div>
        {% endtimezone %}
        {% endwith %}
    </div>
    <div class="row">
        <div class="col-md-6">
            <h3>{% trans "Directory entries" %}</h3>
            <ul>
            {% for entry in entries %}
                <li><a href="{% url 'thedirectory:entry_detail' entry.slug %}">{{ entry.name }}</a>
                (
                <a href="{% url 'thedirectory:category_detail' entry.category.slug %}">{{ entry.category.name }}</a> -
                <a href="{% url 'thecarib:country_detail' entry.country.iso %}">{{ entry.country.name }}
                </a>)
                </li>
            {% empty %}
                <li>{% blocktrans with username=user.get_full_name %}No directory entry for {{ username }}.{%   endblocktrans %}</li>
            {% endfor %}
            </ul>
        </div>
        <div class="col-md-6">
            <h3>{% trans "Events" %}</h3>
            <ul>
            {% for event in events %}
                <li><a href="{% url 'thecalendar:event_detail' event.slug %}">{{ event.summary }}</a></li>
            {% empty %}
                <li>{% blocktrans with username=user %}No event for {{ username }}.{%   endblocktrans %}</li>
            {% endfor %}
            </ul>

        </div>
    </div>
{% endblock %}


{% block footer-js %}
<script>
$(function () {
    $('#profile-page a:first').tab('show');
})
</script>
{% endblock %}