apps/thecalendar/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse_lazy
from django.views.generic import CreateView, UpdateView, DetailView, ListView, TemplateView

from .forms import EventForm
from .models import Category, Event
from .views import fullcalendar_events_json, CategoryDetailView, EventCreateView, EventUpdateView
from thecaribfos.decorators import ownership_required

urlpatterns = [
    #index
    url(r'^agenda/$',
    TemplateView.as_view(
            template_name = 'thecalendar/page_agenda.html'
        ),
        name = 'agenda'
    ),

    # json for zabuto calendar
    url(r'^json$',
        fullcalendar_events_json,
        name = 'fullcalendar_json'
    ),

    # form add event
    url(r'^event/add/$',
        login_required(EventCreateView.as_view()
        ),
        name="form_event_add",
    ),

    # form update event
    url(r'^(?P<slug>[-\w]+)/update/$',
        login_required(ownership_required(EventUpdateView.as_view(), model=Event, owner_field='creation_user')
        ),
        name = 'form_event_update'
    ),

    # event details
    url(r'^(?P<slug>[-\w]+)/$',
        DetailView.as_view(model = Event,
                           context_object_name='event',
                           template_name ='thecalendar/event_detail.html'
        ),
        name = 'event_detail'
    ),


    # Category details
    url(r'^categories/(?P<slug>[-\w\d]+)/$',
        CategoryDetailView.as_view(),
        name = 'category_detail'
    ),

    # Categories list
    url(r'^categories/$',
        ListView.as_view(
            model = Category,
            context_object_name = 'categories',
        ),
        name = "category_list"
    ),
]

apps/thecarib/urls.py
from django.conf.urls import url
#~ from django.core.urlresolvers import reverse_lazy
from django.views.generic import DetailView, ListView
#~
#~
#~ from apps.thedirectory.models import Entry
#~ from apps.thecalendar.models import Event
#~
from .models import Country

from .views import CountryDetail

urlpatterns = [

    url(r'^$',
        ListView.as_view(
            model = Country,
            context_object_name = 'countries'
        ),
        name = 'country_list'
    ),

    url(r'^(?P<slug>[-\w\d]+)/$',
        CountryDetail.as_view(),
        #~ DetailView.as_view(
            #~ model = Country,
            #~ context_object_name = 'country',
            #~ slug_field = 'iso'
        #~ ),
        name = 'country_detail'
    ),

]

apps/thedirectory/urls.py
from django.conf.urls import patterns, include, url
from django.core.urlresolvers import reverse_lazy
from django.contrib.auth.decorators import login_required
from django.views.generic import DetailView, CreateView, ListView, TemplateView

from .forms import EntryForm
from .models import Category, Entry
from .views import CategoryDetailView, EntryCreateView, EntryUpdateView, json_map_entries_by_tags
from thecaribfos.decorators import ownership_required

urlpatterns = [

    # entry details
    url(r'^entries/(?P<slug>[-\w\d]+)/$',
        DetailView.as_view(
            model = Entry,
            context_object_name = 'entry',
            slug_field = 'slug'
        ),
        name = 'entry_detail'
    ),
    # form add entry
    url(r'^entry/add/$',
        login_required(
            EntryCreateView.as_view()
        ),
        name="form_entry_add",
    ),
    # form update entry
    url(r'^entries/(?P<slug>[-\w\d]+)/update/$',
        login_required(ownership_required(EntryUpdateView.as_view(), model=Entry, owner_field='creation_user')
        ),
        name="form_entry_update",
    ),

    # Category details
    url(r'^categories/(?P<slug>[-\w\d]+)/$',
        CategoryDetailView.as_view(),
        name = 'category_detail'
    ),

    # Categories list
    url(r'^categories/$',
        ListView.as_view(
            model = Category,
            context_object_name = 'categories',
        ),
        name = "category_list"
    ),

    # index
    url(r'^map/$',
        TemplateView.as_view(
            template_name = 'thedirectory/map/page_map.html'
        ),
        #~ CreateView.as_view(
            #~ form_class=EntryForm,
            #~ template_name='thedirectory/map/page_map.html',
            #~ success_url=reverse_lazy('success')
        #~ ),
        name = 'map'
    ),
    # (leaflet POI js)
    url(r'^map.js$',
        ListView.as_view(model = Entry,
                         template_name = 'thedirectory/map/map.js'
        ),
        name="map_js"
    ),
    url(r'^map_home.js$',
        ListView.as_view(model = Entry,
                         template_name = 'thedirectory/map/map_home.js'
        ),
        name="map_js"
    ),
    url(r'^map/tag/(?P<tag>[-_A-Za-z0-9]+)/entries.json$',
        json_map_entries_by_tags,
        name = 'json_map_entries_by_tags'
    ),


    #~ (r'^tags/$', 'apps.thedirectory.views.tags'),
    #~ (r'^tag/(?P[-_A-Za-z0-9]+)/$','apps.thedirectory.views.with_tag'),
    #~ (r'^tag/(?P[-_A-Za-z0-9]+)/page/(?Pd+)/$', 'apps.thedirectory.views.with_tag' ),
]

apps/theuser/urls.py
from django.conf.urls import patterns, include, url
from django.core.urlresolvers import reverse_lazy

from .views import UserDetailView

urlpatterns = [
    # user public details
    url(r'^(?P<slug>[-\w]+)/$', UserDetailView.as_view(),
    name = 'user_detail'
    ),
]

thecaribfos/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.contrib.flatpages import views
from django.views.generic import ListView, TemplateView
from django.views.i18n import javascript_catalog

import autocomplete_light.shortcuts as al
from apps.thecalendar.models import Event
from apps.thehomepage.views import HomePageDetailView

js_info_dict = {
    'packages': ('thecaribfos.apps.thedirectory',),
}

urlpatterns = [
    # main index
    url(r'^$',
        #~ ListView.as_view(
            #~ model = Event,
            #~ template_name = 'home.html'
        #~ ),
        HomePageDetailView.as_view(),
        name = 'home'
    ),
    url(r'^calendar/', include("apps.thecalendar.urls", namespace="thecalendar")),
    url(r'^directory/', include("apps.thedirectory.urls", namespace="thedirectory")),

    url(r'^caribbean/', include("apps.thecarib.urls", namespace="thecarib")),
    url(r'^contact/', include('apps.thecontactform.urls', namespace="thecontactform")),

    url(r'^account/', include("account.urls")),
    url(r'^account/$', login_required(TemplateView.as_view(
            template_name = 'account/profile.html')
        ),
        name = 'account_profile'
    ),
    url(r"^account/social/", include("social.apps.django_app.urls", namespace="social")),
    url(r'^user/', include('apps.theuser.urls', namespace='theuser')),
    url(r'^admin/', include(admin.site.urls)),
    # form submission success
    url(r'^contribute/success/$',
        TemplateView.as_view(template_name="include/success.html"),
        name='success'
    ),
    #~ url(r'^markdown/', include('django_bootstrap_markdown.urls')),
    url(r'^autocomplete/', include('autocomplete_light.urls')),
    url(r'^jsi18n/$', javascript_catalog, js_info_dict),
    #~ url(r'^(?P<url>.*/)$', views.flatpage),
]

apps/thecalendar/models.py
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.utils.translation import ugettext as _
from django.contrib.auth.models import User
from taggit.managers import TaggableManager

from apps.thecarib.models import Country

@python_2_unicode_compatible
class Category(models.Model):
    name = models.CharField(_("Name"),
                             max_length=25)
    slug = models.SlugField(_("Slug"),
                            max_length=25)
    description = models.TextField(_("Description"),
                                   max_length=250)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ["name"]
        verbose_name_plural = "Categories"

@python_2_unicode_compatible
class Event(models.Model):

    DRAFT = 'draft'
    PENDING = 'pending'
    PUBLISHED = 'published'
    PUB_STATUS_CHOICES = (
        (DRAFT, _('draft')),
        (PENDING, _('pending')),
        (PUBLISHED, _('published')),
    )

    TENTATIVE = 'tentative'
    CONFIRMED = 'confirmed'
    CANCELLED = 'cancelled'
    STATUS_CHOICES = (
        (TENTATIVE, _("tentative")),
        (CONFIRMED, _("confirmed")),
        (CANCELLED, _("cancelled")),
    )

    country = models.ForeignKey(Country)
    category = models.ForeignKey(Category)
    tags = TaggableManager(verbose_name = _("Tag(s)"),
                           blank=True)
    creation_user = models.ForeignKey(User)
    status = models.CharField(_("Status"),
                              max_length=10,
                              choices=STATUS_CHOICES,
                              default=PENDING)
    dtstart = models.DateTimeField(_("From"))
    dtend = models.DateTimeField(_("To"))
    allday = models.BooleanField(_("All day"))
    summary = models.CharField(_("Title"),
                               max_length=75)
    description = models.TextField(_("Description"),
                                   help_text=_("Use Markdown to format you description text"))
    email = models.EmailField(_("Email"),
                              help_text=_("Email are not published on the website."))
    web = models.URLField(_("Web"),
                               max_length=250)
    #~ location = models.CharField(_("Location"),
                                    #~ max_length=250)
    lat = models.FloatField(_("Latitude"), null=True)
    lon = models.FloatField(_("Longitude"), null=True)
    address = models.TextField(_("Address"),
                               max_length=250)

    slug = models.SlugField(_("Slug"),
                            max_length=100)
    sequence = models.SmallIntegerField(_("Update number"), default=0)
    creation_date = models.DateTimeField(_("Created on"),
                                         auto_now_add=True)
    lastupdate_date = models.DateTimeField(_("Last modification"),
                                         auto_now=True)
    pub_status = models.CharField(_("Publication status"),
                                  max_length=10,
                                  choices=PUB_STATUS_CHOICES,
                                  default=PENDING)

    def __str__(self):
        return self.summary

    def save(self, *args, **kwargs):
        ''' increases the sequence number
        '''
        self.sequence += 1
        super(Event, self).save(*args, **kwargs)

    class Meta:
        ordering = ["dtstart", "country", "summary" ]

apps/thedirectory/models.py
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.utils.translation import ugettext as _
from django.contrib.auth.models import User
from taggit.managers import TaggableManager
from apps.thecarib.models import Country

@python_2_unicode_compatible
class Category(models.Model):
    name = models.CharField(_("Name"),
                             max_length=75)
    slug = models.SlugField(_("Slug"),
                            max_length=25)
    description = models.TextField(_("Description"),
                                   max_length=250,
                                   blank=True)
    def __str__(self):
        return self.name

    class Meta:
        ordering = ["name"]
        verbose_name_plural = "Categories"

@python_2_unicode_compatible
class Entry(models.Model):
    name = models.CharField(_("Name"),
                             max_length=75)
    slug = models.SlugField(_("Slug"),
                            max_length=100)
    country = models.ForeignKey(Country)
    category = models.ForeignKey(Category)
    tags = TaggableManager(verbose_name = _("Tag(s)"),
                           blank=True)
    creation_user = models.ForeignKey(User)
    description = models.TextField(_("Description"),
                                   help_text=_("Use Markdown to format you description text"))
    address = models.TextField(_("Address"), null=True, blank=True)
    email = models.EmailField(_("Email"),
                              help_text=_("Email are not published on the website."))
    web = models.URLField(_("Web"),
                               max_length=250)
    lat = models.FloatField(_("Latitude"), null=True)
    lon = models.FloatField(_("Longitude"), null=True)
    sequence = models.SmallIntegerField(_("Update number"), default=0)
    creation_date = models.DateTimeField(_("Created on"),
                                         auto_now_add=True)
    lastupdate_date = models.DateTimeField(_("Last modification"),
                                         auto_now=True)

    twitter =  models.CharField(_("Twitter account"),
                             max_length=75,
                             null=True,
                             blank=True)
    facebook = models.CharField(_("Facebook page"),
                             max_length=75,
                             null=True,
                             blank=True)
    googleplus = models.CharField(_("Google plus page"),
                             max_length=75,
                             null=True,
                             blank=True)
    linkedin = models.CharField(_("LinkedIn page"),
                             max_length=75,
                             null=True,
                             blank=True)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        ''' increases the sequence number
        '''
        self.sequence += 1
        super(Entry, self).save(*args, **kwargs)

    class Meta:
        ordering = ["name", "country"]
        verbose_name_plural = "Entries"

apps/thecalendar/views.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
import json
import datetime
from django.db.models import Q
from django.core import serializers
from django.core.exceptions import PermissionDenied
from django.core.urlresolvers import reverse
from django.http import HttpResponse
from django.views.generic import CreateView, DetailView, UpdateView
from django.shortcuts import render_to_response
from django.utils import timezone
from django.utils.translation import ugettext as _
from django.core.urlresolvers import reverse_lazy

from django.template import Context, RequestContext
from .models import Category, Event
from .forms import EventForm

class CategoryDetailView(DetailView):
    model = Category
    context_object_name = 'category'
    slug_field = 'slug'

    def get_context_data(self, **kwargs):
        context = super(CategoryDetailView, self).get_context_data(**kwargs)
        context['event_list'] = Event.objects.filter(category=self.object)

        return context

class EventCreateView(CreateView):
    form_class=EventForm
    template_name='thecalendar/page_form_event_add.html'
    success_url=reverse_lazy('success')

    def get_form_kwargs(self):
        kwargs = super(EventCreateView, self).get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs.copy()

class EventUpdateView(UpdateView):
    form_class=EventForm
    model = Event
    slug_field = 'slug'
    template_name = 'thecalendar/page_form_event_add.html'
    success_url = reverse_lazy('success')
    context_object_name = 'event'

    def get_form_kwargs(self):
        kwargs = super(EventUpdateView, self).get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs.copy()


def fullcalendar_events_json(request):
    '''generates events json file needed for fullcalendar
    see http://fullcalendar.io/
    '''

    start = datetime.datetime.strptime(request.GET.get('start', '1970-01-01'), '%Y-%m-%d')
    end = datetime.datetime.strptime(request.GET.get('end', '1970-01-01'), '%Y-%m-%d')

    #events = Event.objects.filter(Q(dtstart__gte=start, dtend__lte=end)|Q(dtstart__lte=start, dtend__gte=end))
    events = Event.objects.all()

    country = request.GET.get('country', False)
    if country:
        events = events.filter(country__iso=country)
    data = []

    for event in events:
        data.append({
        'id': event.id,
        'title': event.summary,
        'start': event.dtstart.strftime('%Y-%m-%d'),
        'end': event.dtend.strftime('%Y-%m-%d'),
        'url': reverse('thecalendar:event_detail', args=[event.slug])
        })
    json_data = json.dumps(data)
    return HttpResponse(json_data, content_type='application/json')

apps/thecalendar/templates/thecalendar/category_detail.html
{% extends 'include/page_panel.html' %}
{% load staticfiles %}
{% load i18n %}
{% load slug2js %}


{% block head_title %}{{ category.name }}{% endblock %}
{% block head %}{% include "thedirectory/map/map_page_header.html" %}{% endblock %}

{% block content-title %}{{ category.name }}{% endblock %}

{% block panel-title %}<a href="{% url 'thedirectory:map' %}" class="btn-link">{% trans 'The caribbean Free Open Source directory' %}</a> / {{ category.name }}{% endblock %}

{% block page-body %}
    <h3>{{ category.name }}</h3>
    {% if category.description %}{{ category.description }}{% endif %}
    <ul>
    {% for entry in entry_list %}
        <li><strong><a href="{% url 'thedirectory:entry_detail' entry.slug %}">{{ entry.name|upper }}</a></strong> (<a href="{% url 'thecarib:country_detail' entry.country.iso %}">{{ entry.country.name }}</a>)<br>
        {% for tag in entry.tags.slugs %}{{ tag }}&nbsp;{% endfor %}<br>
        {{ entry.description|slice:":250" }}
        </li>
    {% empty %}
    <li>{% trans 'Sorry, this category is empty' %}</li>
    {% endfor %}
    </ul>
    <p><a class="btn btn-primary" href="{% url 'thedirectory:form_entry_add' %}" role="button">{% trans 'Add a new organization or people' %}</a></p>
{% endblock %}


{% block panel-footer %}The caribbean free open source organizations and people directory{% endblock %}

{% block post-panel %}<div style="height:350px;" id="map"></div><br>{% endblock %}

{% block see-also %}<ul>
        <li><a href="{% url 'thecarib:country_list' %}">{% trans 'The countries' %}</a></li>
        <li><a href="{% url 'thedirectory:category_list' %}">{% trans 'The directory entries categories' %}</a></li>
        <li><a href="{% url 'thecalendar:category_list' %}">{% trans 'The events categories' %}</a></li>
</ul>{% endblock %}

{% block footer-js %}
<script>
var map = new L.map('map',{fullscreenControl: false,
                            scrollWheelZoom: false,
                            fullscreenControlOptions:{position: 'topleft'}
                          }).setView([19.031, -73.048], 4);
L.tileLayer('http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
    maxZoom: 18,
    attribution: 'Map data &copy; <a href="http://openstreetmap.org">OpenStreetMap</a> contributors, ' +
        '<a href="http://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>'
}).addTo(map);
var markers = L.markerClusterGroup();

{% for entry in entry_list %}
var marker = L.marker(new L.LatLng({{ entry.lat }}, {{ entry.lon }}), { title: "{{ entry.name }}" });
    markers.addLayer(marker);
{% endfor %}
map.addLayer(markers);
map.on();

</script>
{% endblock %}

apps/thecalendar/templates/thecalendar/category_list.html
{% extends 'include/page_panel.html' %}
{% load staticfiles %}
{% load i18n %}

{% block head_title %}{% trans "Categories of events" %}{% endblock %}

{% block content-title %}{% trans "Categories of events" %}{% endblock %}

{% block panel-title %}<a href="{% url 'thecarib:country_list' %}">{% trans 'Caribbean' %}</a> / {% trans "Categories of events" %}'{% endblock %}

{% block page-body %}
    <ul>{% for category in categories %}
        <li><a href="{% url 'thecalendar:category_detail' slug=category.slug %}">{{ category.name }}</a>
        </li>
    {% endfor %}</ul>
{% endblock %}

{% block panel-footer %}The caribbean free open source organizations and people directory{% endblock %}

{% block see-also %}
    <ul>
        <li><a href="{% url 'thecarib:country_list' %}">{% trans 'Carribean' %}</a></li>
        <li><a href="{% url 'thecalendar:category_list' %}">{% trans 'Events categories' %}</a></li>
{% endblock %}</ul>

apps/thecalendar/templates/thecalendar/event_detail.html
{% extends 'page.html' %}
{% load staticfiles %}
{% load i18n %}
{% load django_markdown %}
{% block head_title %}{{ event.summary }}{% endblock %}

{% block head %}
{% include "thedirectory/map/map_page_header.html" %}
{% endblock %}

{% block main-content %}
<section>
    <div class="container">
        <div class="row">
            <h2 class="text-center">{{ event.summary }}</h2>
            <hr class="star-primary">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <div class="pull-right social-links">
                        <a href="{{ event.web }}">
                            <span class="fa-stack fa"><i class="fa fa-globe fa-stack-2x"></i></span>
                        </a>
                        {% if entry.twitter %}
                        <a href="https://twitter.com/{{ entry.twitter }}" class="twitter-social">
                        <span class="fa-stack fa">
                            <i class="fa fa-square fa-stack-2x"></i>
                            <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
                        </span></a>
                        {% endif %}
                        {% if entry.facebook %}
                        <a href="{{ entry.facebook }}" class="facebook-social">
                        <span class="fa-stack fa">
                            <i class="fa fa-square fa-stack-2x"></i>
                            <i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
                        </span></a>
                        {% endif %}
                        {% if entry.googleplus %}
                        <a href="{{ entry.googleplus }}" class="googleplus-social">
                        <span class="fa-stack fa">
                            <i class="fa fa-square fa-stack-2x"></i>
                            <i class="fa fa-googleplus fa-stack-1x fa-inverse"></i>
                        </span></a>

                        {% endif %}
                        {% if entry.linkedin %}
                        <a href="{{ entry.linkedin }} class="linkedin-social">
                        <span class="fa-stack fa">
                            <i class="fa fa-square fa-stack-2x"></i>
                            <i class="fa fa-googleplus fa-stack-1x fa-inverse"></i>
                        </span></a>
                        {% endif %}
                    </div>
                    <h3 class="panel-title">
                        <a href="{% url 'thecarib:country_list' %}">{% trans 'Caribbean' %}</a> /  <a href="{% url 'thecarib:country_detail' event.country.iso %}">{{ event.country.name }}</a> / <a href="{% url 'thecalendar:category_detail' event.category.slug %}">{{ event.category.name}}</a> / {{ event.summary }}</h3>
                </div>
                <div class="panel-body">
                    <h3>{{ event.summary }} <small>{% trans 'by' %} <a href="{% url 'theuser:user_detail' event.creation_user.username %}">{{ event.creation_user.username }}</a></small>
                    {% if request.user.is_authenticated %}
                        {% if request.user.username == event.creation_user.username %}
                        <a href="{% url 'thecalendar:form_event_update' event.slug %}" class="btn btn-default btn-xs">{% trans 'Edit' %}</a>
                        {% endif %}
                    {% else %}
                        <a href="{% url 'thecalendar:form_event_update' event.slug %}" class="btn btn-default btn-xs">{% trans 'Log in' %}</a>
                    {% endif %}</h3>
                    <h4>{{ event.dtstart}}{% if event.dtend != eventdtstart %} - {{ event.dtend}}{% endif %}</h4>
                    {{ event.description|markdown }}
                </div>
                <div class="panel-footer">
                    {% if event.tags %}
                    <ul class="list-inline" style="margin:0;padding:0;">
                        {% for tag in event.tags.slugs %}
                        <li>{{ tag }}</li>
                        {% endfor %}
                    </ul>
                    {% endif %}
                </div>
            </div>
            <div style="height:350px;" id="map">
            </div><br>
            <address>
              <strong>{{ event.name }}</strong><br>
              {% if event.address %}{{ event.address }}<br>{% endif %}
              {{ event.country.name }}<br>
              <a href="{{ event.web }}">{{ event.web }}</a>
            </address>
            <small class="text-muted"><i class="fa fa-user"> </i> {{ event.creation_user.username }}{% if event.creation_date %} <i class="fa fa-calendar"> </i> {{ event.creation_date}}{% endif %}
            {% if event.lastupdate_date != event.creation_date %} <i class="fa fa-pencil-square-o"> </i> {{ event.lastupdate_date}}{% endif %}</small>
            <hr>
        </div>
        <div class="row">
            {% if event.tags.similar_objects %}
                <div class="col-md-6">
                    <h4>{% trans 'See Also' %}</h4>
                    <ul>
                    {% for object in event.tags.similar_objects %}
                        <li><strong><a href="{% url 'thecalendar:event_detail' object.slug %}">{{ object.name|upper }}</a></strong> ({{object.country.name}} / {{object.category.name }})</li>
                    {% endfor %}
                    </ul>
                </div>
            {% endif %}
            <div class="col-md-6">
                {% include 'share_this_page.html' %}
            </div>
        </div>
    </div>
</section>
{% endblock main-content %}

{% block footer-js %}
<script>
var map = new L.map('map',{fullscreenControl: false,
                            scrollWheelZoom: false,
                            fullscreenControlOptions:{position: 'topleft'}
                          }).setView([19.031, -73.048], 4);
L.tileLayer('http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
    maxZoom: 18,
    attribution: 'Map data &copy; <a href="http://openstreetmap.org">OpenStreetMap</a> contributors, ' +
        '<a href="http://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>'
}).addTo(map);

var marker = null;
var found;
marker = L.marker([{{ event.lat }}, {{ event.lon }}]).addTo(map);
//~ map.on(map.setView(([{{ entry.lat }}, {{ entry.lon }}]), 13));
map.on();

</script>
{% endblock %}

apps/thecalendar/templates/thecalendar/fullcalendar_page_footer.html
{% load staticfiles %}

apps/thecalendar/templates/thecalendar/page_form_event_add.html
{% extends 'site_base.html' %}
{% load i18n %}
{% load l10n %}
{% load staticfiles %}
{% load thecarib_tags %}
{% load crispy_forms_tags %}

{% block head_title %}
{% if event %}
    {{ event.summary }} ({% trans 'Edit' %})
{% else %}
    {% trans 'Submit new date' %}
{% endif %}
{% endblock %}

{% block head %}
<link rel='stylesheet' href="{% static 'libs/bower_components/fullcalendar/dist/fullcalendar.css' %}"/>
{% include "thedirectory/map/map_page_header.html" %}
<link href="{% static 'libs/bower_components/bootstrap-markdown/css/bootstrap-markdown.min.css' %}" rel="stylesheet">
{% endblock %}


{% block body-header-content %}
{% endblock %}

{% block main-content %}
<section id="fos-agenda">
<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <h2 class="text-center">{% if event %} {% blocktrans with summary=event.summary %} Edit {{ summary }} {% endblocktrans %} {% else %} {% trans 'Submit new date' %}{% endif %}</h2>
            <hr class="star-primary">
            <p class="text-center">{% trans 'Add your own event into the FOS Carib agenda !' %}</p>
            <hr>
            <form id="frm-fos-entry-add" action="{{ request.get_full_path }}" method="post">
            {% csrf_token %}
            {% crispy form %}

            <div class="text-center">
            <button class="btn btn-primary" type="submit"><i class="fa fa-plus"></i> {% trans 'Save' %}</button>
            <button type="button" class="btn btn-default" data-dismiss="modal"><i class="fa fa-times"></i> {% trans 'Return to the page' %}</button>
            </div>
            </form>
        </div>
    </div>
    </div>
</div>
</section>
{% endblock main-content %}

{% block body-footer-content %}
{% endblock body-footer-content %}


{% block footer-js %}
    {# Custom Full calendar #}
<!--
    <script src="{% static 'libs/bower_components/moment/min/moment.min.js' %}"></script>
    <script src="{% static 'libs/bower_components/fullcalendar/dist/fullcalendar.js' %}"></script>
    <script src="/static/libs/bower_components/fullcalendar/dist/lang/{% get_current_language as LANGUAGE_CODE %}{{ LANGUAGE_CODE }}.js"></script>
    {% include "thecalendar/fullcalendar_page_footer.html" %}
-->
<!--
    <script src="{% static 'libs/bower_components/jquery-form/jquery.form.js' %}"></script>
-->

<script src="{% static 'libs/bower_components/jquery-ui/jquery-ui.min.js' %}"></script>
<script src="{% static 'libs/bower_components/jquery-ui/ui/datepicker.js' %}"></script>
<script type="text/javascript">
$('.datepicker').datepicker();
$('#fosModal').on('hidden.bs.modal', function () {
  $(this).removeData('bs.modal');
})
</script>
{{ form.media }}
<script src="{% static 'libs/bower_components/bootstrap-markdown/js/bootstrap-markdown.js' %}"></script>
<script src="{% static 'libs/bower_components/to-markdown/dist/to-markdown.js' %}"></script>
<script src="{% static 'libs/handly_grabbed_components/markdown.js' %}"></script>
<script type="text/javascript">
$("#id_description").markdown({autofocus:false,savable:false})
</script>
{% endblock %}

{% block analytics %}{% endblock %}